name: Deploy to Production

on:
  pull_request:
    types:
      - closed

jobs:
  deploy_to_production:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Production Server
      run: |
        sshpass -p "${{ secrets.PROD_PASS }}" ssh -o StrictHostKeyChecking=no -p 22456 root@your_prod_server_ip "cd /var/www/html/hemant/myfirstproject && git pull origin main"

