name: Deploy to Dev Server

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy_to_dev_server:
    name: Deploy to Dev Server
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy Code to Dev Server
      run: |
        sshpass -p "${{ secrets.DEV_PASS }}" ssh -o StrictHostKeyChecking=no -p 22456 root@103.171.45.35 "cd /var/www/html/hemant/myfirstproject && git reset --hard HEAD && git clean -df && git pull origin dev"

